export const ACTIONS = Object.freeze({
  CREATE_CASH_ADVANCE: "CREATE_CASH_ADVANCE",
  APPROVE_CASH_ADVANCE: "APPROVE_CASH_ADVANCE",
  CREATE_EXPENSE: "CREATE_EXPENSE",
  APPROVE_EXPENSE: "APPROVE_EXPENSE",
  VIEW_ALL_BRANCHES: "VIEW_ALL_BRANCHES",
  VIEW_LEDGER: "VIEW_LEDGER",
  WRITE_LEDGER: "WRITE_LEDGER",
  CREATE_USER: "CREATE_USER",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
  VIEW_REPORTS: "VIEW_REPORTS",
});

const permissions = {
  CREATE_CASH_ADVANCE: ["BRANCH_MANAGER", "PROGRAM_OFFICER"],
  APPROVE_CASH_ADVANCE: ["FINANCE_HEAD", "ACCOUNTS_HEAD"],
  CREATE_EXPENSE: ["DATA_ENTRY_OPERATOR", "BRANCH_MANAGER"],
  APPROVE_EXPENSE: ["BRANCH_MANAGER", "ACCOUNTS_HEAD"],
  VIEW_ALL_BRANCHES: ["FINANCE_HEAD", "ACCOUNTS_HEAD", "AUDITOR"],
  VIEW_LEDGER: ["FINANCE_HEAD", "ACCOUNTS_HEAD", "AUDITOR"],
  WRITE_LEDGER: ["FINANCE_HEAD", "ACCOUNTS_HEAD"],
  CREATE_USER: ["FINANCE_HEAD"],
  VIEW_AUDIT_LOG: ["AUDITOR", "FINANCE_HEAD"],
  VIEW_REPORTS: ["FINANCE_HEAD", "ACCOUNTS_HEAD", "BRANCH_MANAGER", "DATA_ENTRY_OPERATOR", "PROGRAM_OFFICER", "AUDITOR"],
};

export function can(role, action) {
  return permissions[action]?.includes(role) ?? false;
}
