"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiFetch, type Role } from "@/lib/api";
import Button from "./ui/Button";

type Fund = { id:string; donorName:string; grantName:string; totalAmount:string; currency:string; startDate:string; endDate:string; status:"ACTIVE"|"CLOSED"; allocated:string; spent:string; remaining:string };
type Branch = { id:string; name:string; code:string };
const rolePath:Record<string,string>={FINANCE_HEAD:"finance-head",ACCOUNTS_HEAD:"accounts-head",AUDITOR:"auditor"};
export default function FundsModule({role}:{role:Role}) {
 const [funds,setFunds]=useState<Fund[]>([]); const [branches,setBranches]=useState<Branch[]>([]); const [status,setStatus]=useState(""); const [donor,setDonor]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const canManage=role==="FINANCE_HEAD";
 const load=useCallback(async()=>{try{const q=new URLSearchParams();if(status)q.set("status",status);if(donor)q.set("donor",donor);setFunds(await apiFetch(`/api/funds?${q}`));}catch(e){setMessage(e instanceof Error?e.message:"Could not load funds");}},[status,donor]);
 useEffect(()=>{load();if(canManage)apiFetch<Branch[]>("/api/branches").then(setBranches).catch(()=>setBranches([]));},[load,canManage]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=e.currentTarget,d=new FormData(f);try{await apiFetch("/api/funds",{method:"POST",body:JSON.stringify(Object.fromEntries(d))});f.reset();setMessage("Fund created.");await load();}catch(x){setMessage(x instanceof Error?x.message:"Creation failed");}finally{setBusy(false)}}
 async function allocate(fundId:string,e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=e.currentTarget,d=new FormData(f);try{await apiFetch(`/api/funds/${fundId}/allocate`,{method:"POST",body:JSON.stringify({branchId:d.get("branchId"),allocatedAmount:Number(d.get("allocatedAmount"))})});f.reset();setMessage("Branch allocation saved and ledger deposit posted.");await load();}catch(x){setMessage(x instanceof Error?x.message:"Allocation failed");}finally{setBusy(false)}}
 return <section className="phase-module"><div className="module-heading"><div><span>PHASE 8 · DONOR TRACKING</span><h2>Funds & grants</h2><p>{canManage?"Create grants, allocate branch budgets and monitor utilization.":"Read-only donor fund utilization."}</p></div><strong>{funds.filter(f=>f.status==="ACTIVE").length} active</strong></div>{message&&<div className={`inline-message ${message.includes("failed")||message.includes("Could")?"error":"success"}`}>{message}</div>}
 <div className="report-filters"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="ACTIVE">Active</option><option value="CLOSED">Closed</option></select></label><label>Donor<input value={donor} onChange={e=>setDonor(e.target.value)} placeholder="Search donor"/></label></div>
 {canManage&&<form className="fund-form" onSubmit={create}><label>Donor<input name="donorName" required/></label><label>Grant name<input name="grantName" required/></label><label>Amount<input name="totalAmount" type="number" min=".01" step=".01" required/></label><label>Currency<input name="currency" defaultValue="USD" pattern="[A-Za-z]{3}" required/></label><label>Starts<input name="startDate" type="date" required/></label><label>Ends<input name="endDate" type="date" required/></label><label className="wide-field">Notes<input name="notes"/></label><Button type="submit" disabled={busy}>Create fund</Button></form>}
 <div className="fund-grid">{funds.map(f=><article key={f.id}><div><small>{f.donorName}</small><span className={`status-pill ${f.status.toLowerCase()}`}>{f.status}</span></div><h3>{f.grantName}</h3><strong>{f.currency} {Number(f.totalAmount).toLocaleString()}</strong><div className="fund-stats"><span>Allocated<b>{Number(f.allocated).toLocaleString()}</b></span><span>Spent<b>{Number(f.spent).toLocaleString()}</b></span><span>Remaining<b>{Number(f.remaining).toLocaleString()}</b></span></div><Link href={`/${rolePath[role]}/funds/${f.id}`}>View details →</Link>{canManage&&f.status==="ACTIVE"&&<form onSubmit={e=>allocate(f.id,e)}><select name="branchId" required defaultValue=""><option value="" disabled>Branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="allocatedAmount" type="number" min=".01" step=".01" placeholder="Allocation" required/><Button disabled={busy}>Allocate</Button></form>}</article>)}</div></section>;
}
