"use client";

import { useCallback, useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiFetch, type Role, type SessionUser } from "@/lib/api";
import Button from "./ui/Button";

type Summary = { id: string; name: string; code: string; currentBalance: string; lastActivityAt: string | null };
type Entry = { id: string; type: string; amount: string; runningBalance: string; description: string; createdAt: string; createdBy: { name: string } };
type Ledger = { branch: { name: string; code: string }; currentBalance: string; entries: Entry[] };
const allowed: Role[] = ["FINANCE_HEAD", "ACCOUNTS_HEAD", "AUDITOR"];

export default function LedgerDashboard({ role, user }: { role: Role; user: SessionUser | null }) {
  const [summary, setSummary] = useState<Summary[]>([]); const [selected, setSelected] = useState(""); const [ledger, setLedger] = useState<Ledger | null>(null); const [error, setError] = useState(""); const [expanded, setExpanded] = useState<string | null>(null);
  const loadLedger = useCallback(async (branchId: string) => { setSelected(branchId); setExpanded(null); try { setLedger(await apiFetch<Ledger>(`/api/ledger/${branchId}`)); } catch (e) { setError(e instanceof Error ? e.message : "Could not load ledger"); } }, []);
  useEffect(() => { if (!user || !allowed.includes(role)) return; apiFetch<Summary[]>("/api/ledger/summary").then((data) => { setSummary(data); if (data[0]) loadLedger(data[0].id); }).catch((e) => setError(e.message)); }, [user, role, loadLedger]);
  if (!allowed.includes(role)) return null;
  const chartData = ledger?.entries.map((entry) => ({ ...entry, balance: Number(entry.runningBalance), date: new Date(entry.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }) })) ?? [];
  return <section className="phase-module ledger-module"><div className="module-heading"><div><span>LIVE LEDGER</span><h2>Branch balances</h2><p>Current running balance and complete transaction history.</p></div></div>{error && <div className="inline-message error">{error}</div>}<div className="balance-grid">{summary.map((branch) => <Button key={branch.id} className={selected === branch.id ? "selected" : ""} onClick={() => loadLedger(branch.id)}><small>{branch.name} · {branch.code}</small><strong>${Number(branch.currentBalance).toLocaleString()}</strong><span>{branch.lastActivityAt ? `Updated ${new Date(branch.lastActivityAt).toLocaleDateString()}` : "No activity"}</span></Button>)}</div>{ledger && <><div className="ledger-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="ledgerBalance" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity=".5"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="date" stroke="var(--muted)" tickLine={false}/><YAxis stroke="var(--muted)" tickLine={false}/><Tooltip contentStyle={{ background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 10 }}/><Area type="monotone" dataKey="balance" stroke="var(--accent)" fill="url(#ledgerBalance)" strokeWidth={3} isAnimationActive animationDuration={800} animationEasing="ease-out"/></AreaChart></ResponsiveContainer></div><div className="advance-table-wrap"><table className="advance-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Created by</th><th>Amount</th><th>Running balance</th><th>Details</th></tr></thead><tbody>{ledger.entries.length === 0 ? <tr><td colSpan={7} className="empty-row">No ledger activity for this branch.</td></tr> : ledger.entries.map((entry) => <tr key={entry.id} className={expanded === entry.id ? "expanded-row" : ""}><td>{new Date(entry.createdAt).toLocaleDateString()}</td><td><span className="status-pill disbursed">{entry.type}</span></td><td>{entry.description}{expanded === entry.id && <small className="inline-details">Entry {entry.id} · created {new Date(entry.createdAt).toLocaleString()}</small>}</td><td>{entry.createdBy.name}</td><td className="amount-cell">${Number(entry.amount).toLocaleString()}</td><td className="amount-cell">${Number(entry.runningBalance).toLocaleString()}</td><td><Button className="detail-toggle" onClick={() => setExpanded(expanded === entry.id ? null : entry.id)}>{expanded === entry.id ? "Hide" : "View"}</Button></td></tr>)}</tbody></table></div></>}</section>;
}
